#!/usr/bin/env node
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const raw = JSON.parse(
  await readFile(join(root, 'node_modules/unicode-emoji-json/data-by-emoji.json'), 'utf8'),
);
const ordered = JSON.parse(
  await readFile(join(root, 'node_modules/unicode-emoji-json/data-ordered-emoji.json'), 'utf8'),
);
// emojilib ships a `{ <emoji>: [slug, ...keywords] }` map. Same author as
// unicode-emoji-json; intentionally aligned. The first entry is the canonical
// slug — we drop it (the name already covers that) and keep the rest as
// search keywords ("lol", "haha", ":D", etc.) for ranker matching.
const emojiKeywords = JSON.parse(
  await readFile(join(root, 'node_modules/emojilib/dist/emoji-en-US.json'), 'utf8'),
);

const GROUP_TO_CATEGORY = {
  'Smileys & Emotion': 'smileys-people',
  'People & Body': 'smileys-people',
  'Animals & Nature': 'animals-nature',
  'Food & Drink': 'food-drink',
  'Activities': 'activity',
  'Travel & Places': 'travel-places',
  'Objects': 'objects',
  'Symbols': 'symbols',
  'Flags': 'flags',
  'Component': 'symbols',
};

// SHORTCODE_PATTERN from the SDK: ^:[a-z0-9_+-]{1,32}:$
const SHORTCODE_RE = /^:[a-z0-9_+\-]{1,32}:$/;

const records = [];
let skipped = 0;
for (const char of ordered) {
  const e = raw[char];
  if (!e) continue;
  const shortcode = `:${e.slug}:`;
  if (!SHORTCODE_RE.test(shortcode)) {
    // Slug exceeds 32 chars or contains invalid chars — skip rather than
    // truncate to avoid ambiguous/colliding shortcodes.
    skipped++;
    continue;
  }
  const codepoints = Array.from(char).map((c) => c.codePointAt(0));
  const htmlEntity = codepoints.map((c) => `&#${c};`).join('');
  // Drop the canonical slug (index 0) — it duplicates the name. Keep the rest.
  const kw = emojiKeywords[char];
  const keywords = Array.isArray(kw) ? kw.slice(1) : [];
  records.push({
    char,
    name: e.name,
    shortcode,
    category: GROUP_TO_CATEGORY[e.group] ?? 'objects',
    keywords,
    codepoints,
    htmlEntity,
    ...(e.skin_tone_support ? { skinToneBase: true } : {}),
  });
}

const header = `// AUTO-GENERATED by scripts/generate-data.mjs. Do not edit by hand.
// Regenerate with: pnpm --filter org.asyar.emoji run gen:data
import type { EmojiRecord } from '../lib/types';

// JSON.parse cast avoids TS2590 "union type too complex" on 1900+ record literals.
// Body is double-stringified so the inner JSON survives JS-string escaping
// regardless of what keywords contain (backslashes, backticks, \${, etc.).
export const EMOJIS = JSON.parse(`;
const body = JSON.stringify(JSON.stringify(records));
const footer = `) as EmojiRecord[];\n`;
await writeFile(join(root, 'src/data/emojis.ts'), header + body + footer);
console.log(`Wrote ${records.length} emoji records (skipped ${skipped} with overlong slugs).`);
